function banner()
    println()
    println()
    println(" ____                           ___  ___  ")
    println("|  _ \\ __ _ _ __ __ _ _ __ ___  \\  \\/  / ")
    println("| |_) / _` | '__/ _` | '_ ` _ \\  \\    /     ")
    println("|  __/ (_| | | | (_| | | | | | \\ /    \\")
    println("|_|   \\__,_|_|  \\__,_|_| |_| |_|/__/\\__\\ ")
    println("                                            ")
    println()
    println()
    println()
    println()
end